### ISSUE TITLE
TableMapping do not close Resultset leading to ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by pktripathy** [r5v9/persist#4]
TableMapping.java  do not close resultset and it leaves the open cursors.

When you run big programs with lot of queries you get ORA-01000: maximum open cursors exceeded, although maximum cursor in my oracle database is set to 300.

Please see code that open resultset  after these 2 comments:
         // all column names and types (from db)
        // all primary keys (from db)

adding  resultSet.close(); statement in two places solves the problem.

Otherwise Metadata cursors "SELECT NULL AS table_cat,        c.owner AS table_schem,...." are left open leading to ORA-01000 errors.

Took a while to fix it... please make the changes so that others do not have to spend time solving this error.

Thanks.

**Comment by r5v9** [comment]
can you fix that in a fork and send me a pull request?

**Comment by pktripathy** [comment]
grgz has fixed it already
