### ISSUE TITLE
Should support Collection as a query param type

### ISSUE THREAD

**Issue by jboyens** [r5v9/persist#6]
Doing:

persist.readList(Klass.class, "SELECT \* FROM klass WHERE id IN (?)", listOfIds) 

should just work

**Comment by jboyens** [comment]
Right now the behavior seems to be to dump the serialized version of the list into the query:

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_binary'¬í\0sr\0java.util.ArrayListx?Ò™Ça?\0I\0sizexp\0\0\0w\0\0\0sr\0' at line 1

**Comment by r5v9** [comment]
It would work if you made listOfIds as a String which has a comma separated list of IDs, no?

**Comment by jboyens** [comment]
Yes, it does, but it would be easy enough to detect a collection and join the elements together. Good idea? or sort of useless?

**Comment by pktripathy** [comment]
What about this

```
/**
 * Reads a list of objects from the database by mapping the results of the
 * parameterised SQL query by the each parameter in the parameter List
 * @param <T>  the type of object
 * @param objectClass the object class
 * @param sql the SQL query string
 * @param paramList parameters the query parameters
 * @return the list of objects
 */
public <T> List<T> readListByParamList(final Class<T> objectClass, final String sql, final List<String> paramList) {
    final PreparedStatement stmt = getPreparedStatement(sql);
    final List<T> ret = new ArrayList<>(paramList.size());
    ResultSet resultSet;
    T retObj;
    try {
        for (String param : paramList) {
            stmt.setString(1, param);
            resultSet = stmt.executeQuery();
            if (resultSet.next()) {
                retObj = (T) loadObject(objectClass, resultSet);
                ret.add(retObj);
            }
        }
    } catch (SQLException e) {
        throw new RuntimeSQLException(e);
    }
    if (closePreparedStatementsAfterRead) {
        closePreparedStatement(stmt);
    }
    return ret;
}
```

I use readListByParamList function a lot. This way you do not have to create the statement(parsing) each time, it is done just once.
it works fine for me.
